### ISSUE TITLE
[0.2.0] Blocks don't update that they've been assigned a texture

### ISSUE THREAD

**Issue by duely** [EpicSquid/Blockcraftery#21]
At least not until either a large period of time has elapsed or I manually place another block near them do they seem to pick up.

![](https://thumbs.gfycat.com/GrayShabbyGharial-size_restricted.gif)

**Comment by DatenThielt** [comment]
Is this on a server?  SP Game?

If SP Game what are the specs of the machine running it.  

Are you holding right click or just right clicking each one?

**Comment by EpicSquid** [comment]
Also that looks like it's an older version of blockcraftery, I don't think the update fixes it but do you mind trying?

**Comment by duely** [comment]
Apologies, I didn't realise the in-game version number didn't match up. This is `blockcraftery-1.12.2-1.1.0.jar`.

This is a server, however it's a test server set up running on my machine which was ALSO running the client as well, so I imagine that could be a bit of an issue. However, I wasn't suffering any other issues that could be related to slowness or slow TPS.

I was right clicking individually on each one, and the texture was immediately updated as soon as I placed a block which triggered some sort of chunk update. In fact, I honestly believe it was linked to chunk updates because doing a line, then placing a block, (although I didn't count it), only seemed to affect the blocks in that chunk.
