### ISSUE TITLE
 Do not work with Transparent Modded Blocks in 1.12.2

### ISSUE THREAD

**Issue by TerraS77** [EpicSquid/Blockcraftery#23]
I tried with _Flat colored block, Ender IO, thermal expansion, decocraft, mekanism_, none works. Only glass vanilla can be applied to the blocks... 

https://youtu.be/dCRoUhryhH8

Version 1.12.2-1.1.0, in modpack.

**Comment by AnbaricDragon** [comment]
None of those work for me either
Have additionally tried:
Tiny Progressions - works normally
Extra Utilities 2 - framed blocks accept the glass but always show the texture of the base one with meta:0

**Comment by EpicSquid** [comment]
Finally found out what was causing this (except the exu2 issue, that one is something I don't think I can solve rn)
