### ISSUE TITLE
registered twice

### ISSUE THREAD

**Issue by bookerthegeek** [EpicSquid/Blockcraftery#25]
# Heyo!
Thought you would want to know [this](https://gist.github.com/bookerthegeek/faf3286e0867e34c2544cbe264924144) pops up in the console when starting minecraft.

### Mods
 - [Full List](https://gist.github.com/bookerthegeek/a0f0b398fe9563af2a6e6ffc3cb87444)

**Comment by EpicSquid** [comment]
Oh gosh I'm slightly embarrassed I didn't notice this. Thanks for the kind heads up!

**Comment by EpicSquid** [comment]
OH MY GOSH I WAS SO STUPID

Finally found where I got it wrong. Far out that evaded me for ages
