### ISSUE TITLE
Glowstone dust doesn't work

### ISSUE THREAD

**Issue by mcdodge34** [EpicSquid/Blockcraftery#29]
Your last addition doesn't seem to work for me, it does briefly give light for a split second then the block is dark again and I can give the block as many glowstone as I want, it does eat them, and when we break it, it gives me only 1 glowstone dust back. using forge 2781 and latest version of your mod right now 1.12.2-1.2.0 and mysticalib-1.12.2-1.1.1 I discovered that probably another mod of mine, I suppose its quark, allow me to use glowstone dust like we put redstone dust on the ground, will try to disable this function and try again to see if it could conflict, I see no errors on server side and console of my client doesn't mention anything, just a quick light update and its dark again.

**Comment by EpicSquid** [comment]
Fixed in dev
