### ISSUE TITLE
Slants have black texture errors at certain positions

### ISSUE THREAD

**Issue by erindalc** [EpicSquid/Blockcraftery#3]
Forge: 14.23.4.2756 (MC 1.12.2)
Blockcraftery: 0.1.3

![2018-08-18_04 14 59](https://user-images.githubusercontent.com/12499779/44297319-54bc6c80-a29d-11e8-8874-2e328cdc5899.png)

Other than placing the blocks in the shown orientations (error occurs whether they are given a block or not), I don't have anything special to reproduce it.

**Comment by erindalc** [comment]
Connected Texture Mod if I'm not mistaken

**Comment by Seraphaestus** [comment]
This really sucks so I hope you can fix it soon, it's a serious mod issue.
![2018-10-08_15 47 59](https://user-images.githubusercontent.com/38625872/46616054-a2bd5600-cb11-11e8-9328-54959df8ab60.png)

**Comment by jk1895** [comment]
Have you guys figured out how to fix this? I also added this mod to the Stoneblock pack because I can't live without it. Unfortunately it's not usable with this bug.

**Comment by EpicSquid** [comment]
There is a fix in dev, I'm away this weekend but hopefully I can a get it out next week.

**Comment by jk1895** [comment]
Das ist großartig! Vielen Dank für Ihre Mühe. 👍

**Comment by jk1895** [comment]
Thank you very much for fixing the rendering issue! 👍 :)
