### ISSUE TITLE
Glowstone and Factory Blocks not working together with framed blocks on server pack

### ISSUE THREAD

**Issue by kman3107** [EpicSquid/Blockcraftery#37]
------------------------
Java: 1.8.0_211
MultiMC 5 - Version 0.6.5-1302
Minecreaft: 1.12.2
Forge: 14.23.5.2836
LWJGL 2: 2.9.4-nightly-20150209
Mysticallib: 1.1.1
Blockcraftery: 1.2.0
Chisel 0.2.1.35
-------------------------

I've seen some issues with glowstone and framed blocks and I also have some issues.
My problem is that after I placed down 1 Framed Block, 1 Factory Block and 1 Glowstone Dust and it worked. After that other Framed Blocks will no longer keep their light, it only blinks 0.1 sec.

1. To test I first I made an instance with only the mods above and it worked as intended.
2. I've tested Framed Blocks(Blockcraftery), Glowstone(Minecraft) and Factory Blocks(Chisel)
in a completely new world of the pack I'm having problems with and it works just fine.

All my testing was done SP and my problem is MP and I don't have access to the MP server.
There are also a ton of other mods in the pack, the server constantly lags etc.
The pack is made by some amateur who made lots of changes to things.

I thought I'd just mention this since I loved using Carpenter blocks back in 1.7.10 and
I'd love for Blockcraftery to become the next Carpenter mod.

**Comment by EpicSquid** [comment]
Thanks for the report, i've seen this issue becoming more and more frequent lately. I wil look into it

**Comment by EpicSquid** [comment]
Fixed it now, should be in the next build
