### ISSUE TITLE
Trapdoors and Doors change orientation after re-entering the world or changing dimension

### ISSUE THREAD

**Issue by Insane96** [EpicSquid/Blockcraftery#41]
![2019-05-27_10 39 44](https://user-images.githubusercontent.com/7185104/58407368-ea2a2f80-806b-11e9-9e1f-284cfc0b5d23.png)
![2019-05-27_10 39 57](https://user-images.githubusercontent.com/7185104/58407369-ea2a2f80-806b-11e9-90af-19a43e365e0d.png)

**Comment by AssB0ys** [comment]
Everything else does it too.
![2019-05-27_12 33 19](https://user-images.githubusercontent.com/49584508/58411040-1352bc00-807c-11e9-8d6f-9ed94bba7421.png)

**Comment by HalestormXV** [comment]
I can report the same. With this update it appears all blocks are not keeping their orientation. I just changed about 42 of them lol with the update (as the update changed the orientation). Shut down my server, came back and well they all rotated to a different direction.

**Comment by EpicSquid** [comment]
Well I think I know what the issue is, though I do find it quite strange it's happening. I will put out a hot fix later, but it may disable glowstone working on any block other than a normal block for now

**Comment by EpicSquid** [comment]
Fixed, new release is out now
