### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by MokahTGS** [EpicSquid/Blockcraftery#50]
Forge 2836
Blockcraftery 1.3.1

crash log
https://pastebin.com/MCAD0b6J

full mod list
https://pastebin.com/D2uviWRh

**Comment by MokahTGS** [comment]
Rolling back to 1.2.0 stops the crash

**Comment by EpicSquid** [comment]
Update mystical lib.

**Comment by MokahTGS** [comment]
There is a newer version of MysticalLib than 1.2.1?

The Twitch Launcher doesn't show anything newer.
