### ISSUE TITLE
Suggestion-Doors&Trapdoors

### ISSUE THREAD

**Issue by PurpleHel** [EpicSquid/Blockcraftery#6]
Doors and trapdoors would be nice! It'd be good to have two options tho, with windows and without, so it could either look like a normal trap/door or completely blend into the build.

**Comment by SmokeyTheBandicoot** [comment]
Also would be nice to have Pressure Plates in Carpenter's style, with regulable redstone behaviour (activate for all, only players, only monsters, only items, and any combination).

**Comment by MCrafterzz** [comment]
Are you working on it?

**Comment by EpicSquid** [comment]
Doors and trapdoors are in the next version, as for adding a windowed and non-windowed variety, that will come in a future update.

I am working on the pressure plates as we speak
