### ISSUE TITLE
[Suggestion/Bug] Option to toggle the light

### ISSUE THREAD

**Issue by Jorseii** [EpicSquid/Blockcraftery#7]
I don't know if this is a bug or not, but I made a mob farm and I used the slabs but the slabs get the light get through them so it's not completely dark

Best regards

**Comment by Greg-J** [comment]
Slabs let light through. It's a game mechanic of MC itself. Use solid blocks instead of the slab. There's no reason to add this feature.

**Comment by Jorseii** [comment]
Alright, so we can close the issue. 

Thank you
